# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'administration.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout.addWidget(self.backButton)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lobster")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(1, 90)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.mainTab = QtWidgets.QWidget()
        self.mainTab.setObjectName("mainTab")
        self.formLayoutWidget = QtWidgets.QWidget(self.mainTab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(240, 21, 531, 421))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.formLayoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(14)
        self.gridLayout_4.setVerticalSpacing(32)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.nameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout_4.addWidget(self.nameLabel, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 2, 0, 1, 1)
        self.birthdateLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.birthdateLabel.setFont(font)
        self.birthdateLabel.setObjectName("birthdateLabel")
        self.gridLayout_4.addWidget(self.birthdateLabel, 3, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 4, 0, 1, 1)
        self.positionLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.positionLabel.setFont(font)
        self.positionLabel.setObjectName("positionLabel")
        self.gridLayout_4.addWidget(self.positionLabel, 4, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.patronymicLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.patronymicLabel.setFont(font)
        self.patronymicLabel.setObjectName("patronymicLabel")
        self.gridLayout_4.addWidget(self.patronymicLabel, 2, 1, 1, 1)
        self.surnameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.surnameLabel.setFont(font)
        self.surnameLabel.setObjectName("surnameLabel")
        self.gridLayout_4.addWidget(self.surnameLabel, 0, 1, 1, 1)
        self.salaryLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.salaryLabel.setFont(font)
        self.salaryLabel.setObjectName("salaryLabel")
        self.gridLayout_4.addWidget(self.salaryLabel, 5, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 6, 0, 1, 1)
        self.loginLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loginLabel.setFont(font)
        self.loginLabel.setObjectName("loginLabel")
        self.gridLayout_4.addWidget(self.loginLabel, 6, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 7, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 5, 0, 1, 1)
        self.passwordLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout_4.addWidget(self.passwordLabel, 7, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 2)
        self.gridLayout_4.setColumnStretch(1, 5)
        self.changePasswordButton = QtWidgets.QPushButton(self.mainTab)
        self.changePasswordButton.setGeometry(QtCore.QRect(320, 470, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.changePasswordButton.setFont(font)
        self.changePasswordButton.setObjectName("changePasswordButton")
        self.tabWidget.addTab(self.mainTab, "")
        self.menuTab = QtWidgets.QWidget()
        self.menuTab.setObjectName("menuTab")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.menuTab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 791, 542))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.menuTypeComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.menuTypeComboBox.setObjectName("menuTypeComboBox")
        self.verticalLayout_3.addWidget(self.menuTypeComboBox)
        self.menuTable = QtWidgets.QTableWidget(self.horizontalLayoutWidget_2)
        self.menuTable.setMinimumSize(QtCore.QSize(483, 0))
        self.menuTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.menuTable.setAlternatingRowColors(False)
        self.menuTable.setObjectName("menuTable")
        self.menuTable.setColumnCount(4)
        self.menuTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.menuTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.menuTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.menuTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.menuTable.setHorizontalHeaderItem(3, item)
        self.menuTable.horizontalHeader().setCascadingSectionResizes(False)
        self.menuTable.horizontalHeader().setDefaultSectionSize(116)
        self.menuTable.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.menuTable)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.deleteDishButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.deleteDishButton.setObjectName("deleteDishButton")
        self.horizontalLayout_4.addWidget(self.deleteDishButton)
        self.editDishButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.editDishButton.setObjectName("editDishButton")
        self.horizontalLayout_4.addWidget(self.editDishButton)
        self.addDishButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.addDishButton.setObjectName("addDishButton")
        self.horizontalLayout_4.addWidget(self.addDishButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout.setHorizontalSpacing(14)
        self.gridLayout.setVerticalSpacing(70)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.dishTypeComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dishTypeComboBox.setFont(font)
        self.dishTypeComboBox.setObjectName("dishTypeComboBox")
        self.gridLayout.addWidget(self.dishTypeComboBox, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.dishOutputEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dishOutputEdit.setFont(font)
        self.dishOutputEdit.setObjectName("dishOutputEdit")
        self.gridLayout.addWidget(self.dishOutputEdit, 2, 1, 1, 1)
        self.dishNameEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dishNameEdit.setFont(font)
        self.dishNameEdit.setObjectName("dishNameEdit")
        self.gridLayout.addWidget(self.dishNameEdit, 0, 1, 1, 1)
        self.dishEnergyEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dishEnergyEdit.setFont(font)
        self.dishEnergyEdit.setObjectName("dishEnergyEdit")
        self.gridLayout.addWidget(self.dishEnergyEdit, 3, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 0, 1, 1)
        self.dishPriceEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dishPriceEdit.setFont(font)
        self.dishPriceEdit.setObjectName("dishPriceEdit")
        self.gridLayout.addWidget(self.dishPriceEdit, 4, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.tabWidget.addTab(self.menuTab, "")
        self.staffTab = QtWidgets.QWidget()
        self.staffTab.setObjectName("staffTab")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.staffTab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 791, 531))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.employeesTable = QtWidgets.QTableWidget(self.horizontalLayoutWidget_3)
        self.employeesTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.employeesTable.setObjectName("employeesTable")
        self.employeesTable.setColumnCount(3)
        self.employeesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.employeesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.employeesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.employeesTable.setHorizontalHeaderItem(2, item)
        self.employeesTable.horizontalHeader().setDefaultSectionSize(155)
        self.horizontalLayout_5.addWidget(self.employeesTable)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.deleteEmployeeButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.deleteEmployeeButton.setObjectName("deleteEmployeeButton")
        self.horizontalLayout_6.addWidget(self.deleteEmployeeButton)
        self.editEmployeeButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.editEmployeeButton.setObjectName("editEmployeeButton")
        self.horizontalLayout_6.addWidget(self.editEmployeeButton)
        self.addEmployeeButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.addEmployeeButton.setObjectName("addEmployeeButton")
        self.horizontalLayout_6.addWidget(self.addEmployeeButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 4, -1, -1)
        self.gridLayout_2.setSpacing(16)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 4, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 5, 0, 1, 1)
        self.employeePositionEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.employeePositionEdit.setFont(font)
        self.employeePositionEdit.setObjectName("employeePositionEdit")
        self.gridLayout_2.addWidget(self.employeePositionEdit, 4, 1, 1, 1)
        self.employeeSalaryEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.employeeSalaryEdit.setFont(font)
        self.employeeSalaryEdit.setObjectName("employeeSalaryEdit")
        self.gridLayout_2.addWidget(self.employeeSalaryEdit, 5, 1, 1, 1)
        self.employeePasswordEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.employeePasswordEdit.setFont(font)
        self.employeePasswordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.employeePasswordEdit.setObjectName("employeePasswordEdit")
        self.gridLayout_2.addWidget(self.employeePasswordEdit, 7, 1, 1, 1)
        self.employeePatronymicEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.employeePatronymicEdit.setFont(font)
        self.employeePatronymicEdit.setObjectName("employeePatronymicEdit")
        self.gridLayout_2.addWidget(self.employeePatronymicEdit, 2, 1, 1, 1)
        self.employeeLoginEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.employeeLoginEdit.setFont(font)
        self.employeeLoginEdit.setObjectName("employeeLoginEdit")
        self.gridLayout_2.addWidget(self.employeeLoginEdit, 6, 1, 1, 1)
        self.employeeBirthDateEdit = QtWidgets.QDateEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.employeeBirthDateEdit.setFont(font)
        self.employeeBirthDateEdit.setObjectName("employeeBirthDateEdit")
        self.gridLayout_2.addWidget(self.employeeBirthDateEdit, 3, 1, 1, 1)
        self.employeeSurnameEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.employeeSurnameEdit.setFont(font)
        self.employeeSurnameEdit.setObjectName("employeeSurnameEdit")
        self.gridLayout_2.addWidget(self.employeeSurnameEdit, 0, 1, 1, 1)
        self.employeeNameEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.employeeNameEdit.setFont(font)
        self.employeeNameEdit.setObjectName("employeeNameEdit")
        self.gridLayout_2.addWidget(self.employeeNameEdit, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(16)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.menuCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menuCheckBox.setFont(font)
        self.menuCheckBox.setObjectName("menuCheckBox")
        self.gridLayout_3.addWidget(self.menuCheckBox, 0, 0, 1, 1)
        self.ordersCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ordersCheckBox.setFont(font)
        self.ordersCheckBox.setObjectName("ordersCheckBox")
        self.gridLayout_3.addWidget(self.ordersCheckBox, 2, 0, 1, 1)
        self.employeesCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.employeesCheckBox.setFont(font)
        self.employeesCheckBox.setObjectName("employeesCheckBox")
        self.gridLayout_3.addWidget(self.employeesCheckBox, 1, 0, 1, 1)
        self.menuReadOnlyCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menuReadOnlyCheckBox.setFont(font)
        self.menuReadOnlyCheckBox.setObjectName("menuReadOnlyCheckBox")
        self.gridLayout_3.addWidget(self.menuReadOnlyCheckBox, 0, 1, 1, 1)
        self.employeesReadOnlyCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.employeesReadOnlyCheckBox.setFont(font)
        self.employeesReadOnlyCheckBox.setObjectName("employeesReadOnlyCheckBox")
        self.gridLayout_3.addWidget(self.employeesReadOnlyCheckBox, 1, 1, 1, 1)
        self.ordersReadOnlyCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ordersReadOnlyCheckBox.setFont(font)
        self.ordersReadOnlyCheckBox.setObjectName("ordersReadOnlyCheckBox")
        self.gridLayout_3.addWidget(self.ordersReadOnlyCheckBox, 2, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.verticalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 1)
        self.tabWidget.addTab(self.staffTab, "")
        self.ordersTab = QtWidgets.QWidget()
        self.ordersTab.setObjectName("ordersTab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.ordersTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 791, 531))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ordersTable = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.ordersTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.ordersTable.setObjectName("ordersTable")
        self.ordersTable.setColumnCount(2)
        self.ordersTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ordersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ordersTable.setHorizontalHeaderItem(1, item)
        self.ordersTable.horizontalHeader().setDefaultSectionSize(155)
        self.horizontalLayout_3.addWidget(self.ordersTable)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.orderTable = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.orderTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.orderTable.setObjectName("orderTable")
        self.orderTable.setColumnCount(4)
        self.orderTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(3, item)
        self.orderTable.horizontalHeader().setDefaultSectionSize(116)
        self.verticalLayout_4.addWidget(self.orderTable)
        self.closeOrderButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.closeOrderButton.setObjectName("closeOrderButton")
        self.verticalLayout_4.addWidget(self.closeOrderButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 3)
        self.tabWidget.addTab(self.ordersTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backButton.setText(_translate("MainWindow", "Назад"))
        self.label.setText(_translate("MainWindow", "                                       Администрирование"))
        self.nameLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_19.setText(_translate("MainWindow", "Дата рождения:"))
        self.label_18.setText(_translate("MainWindow", "Отчество:"))
        self.birthdateLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_17.setText(_translate("MainWindow", "Имя:"))
        self.label_20.setText(_translate("MainWindow", "Должность:"))
        self.positionLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "Фамилия:"))
        self.patronymicLabel.setText(_translate("MainWindow", "TextLabel"))
        self.surnameLabel.setText(_translate("MainWindow", "TextLabel"))
        self.salaryLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_22.setText(_translate("MainWindow", "Логин:"))
        self.loginLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_23.setText(_translate("MainWindow", "Пароль:"))
        self.label_21.setText(_translate("MainWindow", "Оклад:"))
        self.passwordLabel.setText(_translate("MainWindow", "TextLabel"))
        self.changePasswordButton.setText(_translate("MainWindow", "Сменить пароль"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainTab), _translate("MainWindow", "Личный кабинет"))
        self.menuTable.setSortingEnabled(True)
        item = self.menuTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Название"))
        item = self.menuTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Выход"))
        item = self.menuTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Калорийность"))
        item = self.menuTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Цена"))
        self.deleteDishButton.setText(_translate("MainWindow", "Удалить"))
        self.editDishButton.setText(_translate("MainWindow", "Изменить"))
        self.addDishButton.setText(_translate("MainWindow", "Добавить"))
        self.label_5.setText(_translate("MainWindow", "Цена"))
        self.label_2.setText(_translate("MainWindow", "Название"))
        self.label_3.setText(_translate("MainWindow", "Тип"))
        self.label_4.setText(_translate("MainWindow", "Выход"))
        self.label_16.setText(_translate("MainWindow", "Калорийность"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.menuTab), _translate("MainWindow", "Меню"))
        item = self.employeesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ФИО"))
        item = self.employeesTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Логин"))
        item = self.employeesTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Должность"))
        self.deleteEmployeeButton.setText(_translate("MainWindow", "Удалить"))
        self.editEmployeeButton.setText(_translate("MainWindow", "Изменить"))
        self.addEmployeeButton.setText(_translate("MainWindow", "Добавить"))
        self.label_6.setText(_translate("MainWindow", "Фамилия"))
        self.label_8.setText(_translate("MainWindow", "Пароль"))
        self.label_10.setText(_translate("MainWindow", "Отчество"))
        self.label_9.setText(_translate("MainWindow", "Логин"))
        self.label_7.setText(_translate("MainWindow", "Имя"))
        self.label_11.setText(_translate("MainWindow", "Дата рождения"))
        self.label_13.setText(_translate("MainWindow", "Должность"))
        self.label_12.setText(_translate("MainWindow", "Оклад"))
        self.label_14.setText(_translate("MainWindow", "              Права доступа"))
        self.menuCheckBox.setText(_translate("MainWindow", "Меню"))
        self.ordersCheckBox.setText(_translate("MainWindow", "Заказы"))
        self.employeesCheckBox.setText(_translate("MainWindow", "Сотрудники"))
        self.menuReadOnlyCheckBox.setText(_translate("MainWindow", "Только просмотр"))
        self.employeesReadOnlyCheckBox.setText(_translate("MainWindow", "Только просмотр"))
        self.ordersReadOnlyCheckBox.setText(_translate("MainWindow", "Только просмотр"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.staffTab), _translate("MainWindow", "Сотрудники"))
        item = self.ordersTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Номер"))
        item = self.ordersTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Время"))
        item = self.orderTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Название"))
        item = self.orderTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Выход"))
        item = self.orderTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Количество"))
        item = self.orderTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Стоимость"))
        self.closeOrderButton.setText(_translate("MainWindow", "Закрыть заказ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ordersTab), _translate("MainWindow", "Заказы"))

