# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customer.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.typesComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.typesComboBox.setObjectName("typesComboBox")
        self.horizontalLayout_4.addWidget(self.typesComboBox)
        self.minusButton = QtWidgets.QPushButton(self.centralwidget)
        self.minusButton.setObjectName("minusButton")
        self.horizontalLayout_4.addWidget(self.minusButton)
        self.plusButon = QtWidgets.QPushButton(self.centralwidget)
        self.plusButon.setObjectName("plusButon")
        self.horizontalLayout_4.addWidget(self.plusButon)
        self.horizontalLayout_4.setStretch(0, 90)
        self.horizontalLayout_4.setStretch(1, 5)
        self.horizontalLayout_4.setStretch(2, 5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.menuTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.menuTableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.menuTableWidget.setObjectName("menuTableWidget")
        self.menuTableWidget.setColumnCount(3)
        self.menuTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.menuTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.menuTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.menuTableWidget.setHorizontalHeaderItem(2, item)
        self.menuTableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.menuTableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.menuTableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.verticalLayout_9.addWidget(self.menuTableWidget)
        self.verticalLayout_9.setStretch(1, 5)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Lobster")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.mainMenuButton = QtWidgets.QPushButton(self.centralwidget)
        self.mainMenuButton.setObjectName("mainMenuButton")
        self.horizontalLayout_2.addWidget(self.mainMenuButton)
        self.horizontalLayout_2.setStretch(0, 3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.billTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.billTableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.billTableWidget.setObjectName("billTableWidget")
        self.billTableWidget.setColumnCount(4)
        self.billTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.billTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.billTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.billTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.billTableWidget.setHorizontalHeaderItem(3, item)
        self.billTableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.billTableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.billTableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.verticalLayout_8.addWidget(self.billTableWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Lobster")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.priceLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Lobster")
        font.setPointSize(14)
        self.priceLabel.setFont(font)
        self.priceLabel.setObjectName("priceLabel")
        self.horizontalLayout_6.addWidget(self.priceLabel)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Lobster")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.horizontalLayout_6.setStretch(2, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_5.addWidget(self.cancelButton)
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout_5.addWidget(self.confirmButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.plusButon.setText(_translate("MainWindow", "+"))
        self.menuTableWidget.setSortingEnabled(True)
        item = self.menuTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Название"))
        item = self.menuTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Выход"))
        item = self.menuTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Цена"))
        self.label.setText(_translate("MainWindow", "Ваш заказ"))
        self.mainMenuButton.setText(_translate("MainWindow", "Главное меню"))
        item = self.billTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Название"))
        item = self.billTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Выход"))
        item = self.billTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Количество"))
        item = self.billTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Стоимость"))
        self.label_4.setText(_translate("MainWindow", "Итого:"))
        self.priceLabel.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "BYN"))
        self.cancelButton.setText(_translate("MainWindow", "Отменить заказ"))
        self.confirmButton.setText(_translate("MainWindow", "Подтвердить заказ"))

